apiVersion: v1
kind: Service
metadata:
  name: kubepipeline-service
spec:
  type: NodePort
  selector:
    app: kubepipeline
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080

